from __future__ import annotations

from typing import Dict

EN: Dict[str, str] = {
    "m_build": "🛠 Build the funnel",
    "w_home": "Funnel builder. Everything you change here is saved to funnel.yaml and applies at once.\nSteps: {steps}, products: {products}. Start step: {start}. Language: {language}.",
    "w_steps": "📋 Steps",
    "w_products": "🛍 Products",
    "w_payments": "💳 Payments and language",
    "w_view": "▶️ See it as a customer",
    "w_steps_text": "Your steps. A step is one message the customer sees. Tap one to edit it, or add a new one.",
    "w_new_step": "➕ New step",
    "w_ask_step_text": "Send me the text of the message. You can use <b>bold</b>, and {{first_name}} for the customer's name.",
    "w_no_step": "No such step.",
    "w_start_mark": "(start)",
    "w_step_title": "Step {id} {start}",
    "w_step_text": "Text: {text}",
    "w_step_image": "Picture: {state}",
    "w_step_button": "Button {n}: «{text}» {what}",
    "w_step_nudge": "Reminder after {after}: {text}",
    "w_step_ask": "Question: saves the answer as {answer} ({kind}), then goes to {next}",
    "w_b_text": "✏️ Text",
    "w_b_image": "🖼 Picture",
    "w_b_addbtn": "➕ Button",
    "w_b_delbtn": "🗑 Button",
    "w_b_nudge": "⏰ Reminders",
    "w_b_ask": "❓ Ask a question",
    "w_b_start": "⭐ Make it the start",
    "w_b_delete": "🗑 Delete step",
    "w_do_goto": "→ step {step}",
    "w_do_pay": "→ buy «{product}»",
    "w_do_url": "→ link {url}",
    "w_do_manager": "→ calls the manager",
    "w_do_back": "→ back",
    "w_do_home": "→ start",
    "w_ask_image": "Send me a picture (as a photo, not as a file).",
    "w_remove_image": "Remove the picture",
    "w_need_photo": "I need a photo. Send it as a photo, not as a file.",
    "w_question_no_buttons": "This step asks a question, so it cannot have buttons. Remove the question first.",
    "w_choose_type": "What should the button do?",
    "w_t_goto": "➡️ Go to a step",
    "w_t_pay": "💳 Buy a product",
    "w_t_url": "🔗 Open a link",
    "w_t_manager": "👨‍💼 Call the manager",
    "w_t_back": "↩️ Back",
    "w_t_home": "🏠 To the start",
    "w_choose_target": "Which step should the button open?",
    "w_choose_product": "Which product should the button sell?",
    "w_no_products": "There are no products yet. Create one in Products first.",
    "w_ask_url": "Send me the link (it must start with https://).",
    "w_bad_url": "That is not a link. It must start with https:// or http://.",
    "w_ask_button_text": "Send me the text that will be written on the button.",
    "w_choose_color": "Pick the colour of the button.",
    "w_c_blue": "🔵 Blue",
    "w_c_green": "🟢 Green",
    "w_c_red": "🔴 Red",
    "w_c_plain": "⚪ Plain",
    "w_draft_gone": "The draft is gone. Start adding the button again.",
    "w_no_buttons": "This step has no buttons.",
    "w_choose_delete": "Tap what to delete.",
    "w_nudge_menu": "A reminder is sent if the customer stays on this step and does nothing. It repeats the step's buttons. Tap an existing one to delete it, or choose when to send a new one.",
    "w_d_1h": "after 1 hour",
    "w_d_3h": "after 3 hours",
    "w_d_1d": "after 1 day",
    "w_d_3d": "after 3 days",
    "w_ask_nudge_text": "Send me the text of the reminder.",
    "w_question_menu": "Ask the customer for information. Their answer is saved, shown in the customer card and exported to CSV. Choose the kind of answer.",
    "w_q_text": "Text",
    "w_q_email": "Email",
    "w_q_phone": "Phone",
    "w_q_number": "Number",
    "w_q_remove": "Remove the question",
    "w_need_other_step": "You need another step to continue to after the answer. Create it first.",
    "w_question_next": "Which step comes after the customer answers?",
    "w_confirm_delete_step": "Delete this step? Buttons that lead to it are removed too.",
    "w_yes_delete": "Yes, delete",
    "w_products_text": "Your products. A product is what the customer buys and gets after paying.",
    "w_new_product": "➕ New product",
    "w_no_product": "No such product.",
    "w_prod_title": "Product «{title}» ({id})",
    "w_prod_desc": "Description: {text}",
    "w_prod_prices": "Prices: {prices}",
    "w_prod_access": "Gives: {what}",
    "w_prod_no_access": "It gives nothing yet. Add what the customer receives after paying.",
    "w_acc_channel": "access to channel {chat}, {days}",
    "w_acc_message": "a message «{text}», files: {files}",
    "w_acc_manager": "a request to the manager",
    "w_days": "{n} days",
    "w_forever": "forever",
    "w_p_title": "✏️ Name",
    "w_p_desc": "✏️ Description",
    "w_p_prices": "💰 Prices",
    "w_p_addaccess": "➕ What they get",
    "w_p_delaccess": "🗑 Remove a gift",
    "w_p_delete": "🗑 Delete product",
    "w_no_currency": "No payment method is on. Turn on Telegram Stars in «Payments and language» first.",
    "w_ask_product_title": "Send me the name of the product.",
    "w_ask_product_desc": "Send me a short description.",
    "w_skip": "Skip",
    "w_ask_price": "Send me the price in {currency} as a number.",
    "w_bad_price": "That is not a valid price. Send a positive number (Stars must be a whole number).",
    "w_product_hint": "Next add what the customer gets after paying: press «What they get». To sell it, add a «Buy a product» button to a step.",
    "w_prices_menu": "Prices per currency. Tap one to change it. A product can be paid only by methods that match its currencies.",
    "w_remove_price": "🗑 Remove {currency}",
    "w_access_menu": "What does the customer get after paying?",
    "w_a_channel": "📢 Access to a private channel",
    "w_a_message": "📄 A message and a file",
    "w_a_manager": "👨‍💼 A request to the manager",
    "w_ask_channel": "Send me the channel id. Add the bot to the channel as an administrator (invite users and ban users), then post /id in the channel: the bot replies with the number.",
    "w_bad_channel": "That is not a channel id. It is a number like -1001234567890.",
    "w_channel_problem": "⚠️ Note: {problem}. Fix it before real customers pay (see the Health check).",
    "w_choose_days": "For how long?",
    "w_ask_message": "Send me the text that the customer receives after paying.",
    "w_ask_file": "Send me the file as a document (a PDF, an archive, ...), or skip.",
    "w_no_file": "No file",
    "w_need_document": "I need a file sent as a document (use the paperclip, «File»).",
    "w_ask_manager_text": "Send me the text the customer sees after paying, for example «We will contact you soon».",
    "w_no_access": "This product gives nothing yet.",
    "w_confirm_delete_product": "Delete this product? Buy buttons for it are removed too.",
    "w_pay_title": "Payments and language",
    "w_pay_on": "✅ {method}: on ({currency})",
    "w_pay_off": "▫️ {method}: off",
    "w_method_stars": "Telegram Stars",
    "w_method_telegram": "Bank cards (Telegram)",
    "w_method_yookassa": "YooKassa",
    "w_method_crypto": "Crypto Pay",
    "w_method_manual": "Manual transfer",
    "w_pay_more": "Cards, YooKassa, crypto and manual transfer need keys from those services; see the payments guide in the documentation.",
    "w_pay_test": "Test mode (free test payment for admins): {state}",
    "w_pay_language": "Bot language: {language}",
    "w_stars_on": "Turn on Telegram Stars",
    "w_stars_off": "Turn off Telegram Stars",
    "w_test_on": "Turn on test mode",
    "w_test_off": "Turn off test mode",
    "w_switch_language": "🌐 Switch language (ru/en)",
    "w_manager_state": "Manager chat: {state}. To set it, add the bot to a group and send /managerchat there.",
    "w_manager_set": "Done: this chat is now the manager chat. Order cards and payment screenshots will arrive here.",
    "w_unavailable": "The builder needs the funnel file, which this run does not have.",
    "w_error": "Could not save this change, nothing was changed:\n{error}",
}

RU: Dict[str, str] = {
    "m_build": "🛠 Собрать воронку",
    "w_home": "Конструктор воронки. Всё, что вы меняете здесь, сохраняется в funnel.yaml и действует сразу.\nШагов: {steps}, продуктов: {products}. Стартовый шаг: {start}. Язык: {language}.",
    "w_steps": "📋 Шаги",
    "w_products": "🛍 Продукты",
    "w_payments": "💳 Оплаты и язык",
    "w_view": "▶️ Посмотреть глазами клиента",
    "w_steps_text": "Ваши шаги. Шаг — это одно сообщение, которое видит клиент. Нажмите на шаг, чтобы изменить его, или добавьте новый.",
    "w_new_step": "➕ Новый шаг",
    "w_ask_step_text": "Пришлите текст сообщения. Можно использовать <b>жирный</b> и {{first_name}} для имени клиента.",
    "w_no_step": "Такого шага нет.",
    "w_start_mark": "(стартовый)",
    "w_step_title": "Шаг {id} {start}",
    "w_step_text": "Текст: {text}",
    "w_step_image": "Картинка: {state}",
    "w_step_button": "Кнопка {n}: «{text}» {what}",
    "w_step_nudge": "Напоминание через {after}: {text}",
    "w_step_ask": "Вопрос: ответ сохраняется как {answer} ({kind}), затем переход на {next}",
    "w_b_text": "✏️ Текст",
    "w_b_image": "🖼 Картинка",
    "w_b_addbtn": "➕ Кнопка",
    "w_b_delbtn": "🗑 Кнопка",
    "w_b_nudge": "⏰ Напоминания",
    "w_b_ask": "❓ Задать вопрос",
    "w_b_start": "⭐ Сделать стартовым",
    "w_b_delete": "🗑 Удалить шаг",
    "w_do_goto": "→ шаг {step}",
    "w_do_pay": "→ купить «{product}»",
    "w_do_url": "→ ссылка {url}",
    "w_do_manager": "→ вызывает менеджера",
    "w_do_back": "→ назад",
    "w_do_home": "→ в начало",
    "w_ask_image": "Пришлите картинку (как фото, а не как файл).",
    "w_remove_image": "Убрать картинку",
    "w_need_photo": "Нужно фото. Отправьте его как фото, а не как файл.",
    "w_question_no_buttons": "Этот шаг задаёт вопрос, поэтому кнопок у него быть не может. Сначала уберите вопрос.",
    "w_choose_type": "Что должна делать кнопка?",
    "w_t_goto": "➡️ Перейти на шаг",
    "w_t_pay": "💳 Купить продукт",
    "w_t_url": "🔗 Открыть ссылку",
    "w_t_manager": "👨‍💼 Позвать менеджера",
    "w_t_back": "↩️ Назад",
    "w_t_home": "🏠 В начало",
    "w_choose_target": "Какой шаг должна открывать кнопка?",
    "w_choose_product": "Какой продукт должна продавать кнопка?",
    "w_no_products": "Продуктов пока нет. Сначала создайте продукт в разделе «Продукты».",
    "w_ask_url": "Пришлите ссылку (она должна начинаться с https://).",
    "w_bad_url": "Это не ссылка. Она должна начинаться с https:// или http://.",
    "w_ask_button_text": "Пришлите текст, который будет написан на кнопке.",
    "w_choose_color": "Выберите цвет кнопки.",
    "w_c_blue": "🔵 Синяя",
    "w_c_green": "🟢 Зелёная",
    "w_c_red": "🔴 Красная",
    "w_c_plain": "⚪ Обычная",
    "w_draft_gone": "Черновик потерян. Начните добавлять кнопку заново.",
    "w_no_buttons": "У этого шага нет кнопок.",
    "w_choose_delete": "Нажмите на то, что нужно удалить.",
    "w_nudge_menu": "Напоминание отправляется, если клиент остался на этом шаге и ничего не делает. Оно повторяет кнопки шага. Нажмите на существующее, чтобы удалить его, или выберите, когда отправить новое.",
    "w_d_1h": "через 1 час",
    "w_d_3h": "через 3 часа",
    "w_d_1d": "через 1 день",
    "w_d_3d": "через 3 дня",
    "w_ask_nudge_text": "Пришлите текст напоминания.",
    "w_question_menu": "Запросите у клиента информацию. Ответ сохраняется, виден в карточке клиента и выгружается в CSV. Выберите вид ответа.",
    "w_q_text": "Текст",
    "w_q_email": "Email",
    "w_q_phone": "Телефон",
    "w_q_number": "Число",
    "w_q_remove": "Убрать вопрос",
    "w_need_other_step": "Нужен ещё один шаг, на который перейти после ответа. Сначала создайте его.",
    "w_question_next": "Какой шаг идёт после ответа клиента?",
    "w_confirm_delete_step": "Удалить этот шаг? Кнопки, которые ведут на него, тоже удалятся.",
    "w_yes_delete": "Да, удалить",
    "w_products_text": "Ваши продукты. Продукт — это то, что клиент покупает и получает после оплаты.",
    "w_new_product": "➕ Новый продукт",
    "w_no_product": "Такого продукта нет.",
    "w_prod_title": "Продукт «{title}» ({id})",
    "w_prod_desc": "Описание: {text}",
    "w_prod_prices": "Цены: {prices}",
    "w_prod_access": "Выдаёт: {what}",
    "w_prod_no_access": "Пока ничего не выдаёт. Добавьте, что клиент получит после оплаты.",
    "w_acc_channel": "доступ в канал {chat}, {days}",
    "w_acc_message": "сообщение «{text}», файлов: {files}",
    "w_acc_manager": "заявку менеджеру",
    "w_days": "{n} дн.",
    "w_forever": "навсегда",
    "w_p_title": "✏️ Название",
    "w_p_desc": "✏️ Описание",
    "w_p_prices": "💰 Цены",
    "w_p_addaccess": "➕ Что получит клиент",
    "w_p_delaccess": "🗑 Убрать выдачу",
    "w_p_delete": "🗑 Удалить продукт",
    "w_no_currency": "Ни один способ оплаты не включён. Сначала включите Telegram Stars в разделе «Оплаты и язык».",
    "w_ask_product_title": "Пришлите название продукта.",
    "w_ask_product_desc": "Пришлите короткое описание.",
    "w_skip": "Пропустить",
    "w_ask_price": "Пришлите цену в {currency} числом.",
    "w_bad_price": "Это не цена. Пришлите положительное число (Stars — целое число).",
    "w_product_hint": "Теперь добавьте, что клиент получит после оплаты: нажмите «Что получит клиент». Чтобы продавать продукт, добавьте кнопку «Купить продукт» на нужный шаг.",
    "w_prices_menu": "Цены по валютам. Нажмите на валюту, чтобы изменить цену. Продукт можно оплатить только способами, подходящими по валюте.",
    "w_remove_price": "🗑 Убрать {currency}",
    "w_access_menu": "Что клиент получает после оплаты?",
    "w_a_channel": "📢 Доступ в закрытый канал",
    "w_a_message": "📄 Сообщение и файл",
    "w_a_manager": "👨‍💼 Заявка менеджеру",
    "w_ask_channel": "Пришлите id канала. Добавьте бота в канал администратором (приглашать и блокировать пользователей), затем опубликуйте в канале /id: бот ответит числом.",
    "w_bad_channel": "Это не id канала. Он выглядит как число -1001234567890.",
    "w_channel_problem": "⚠️ Внимание: {problem}. Исправьте это до того, как заплатят настоящие клиенты (см. «Проверка бота»).",
    "w_choose_days": "На какой срок?",
    "w_ask_message": "Пришлите текст, который клиент получит после оплаты.",
    "w_ask_file": "Пришлите файл как документ (PDF, архив и т. п.) или пропустите.",
    "w_no_file": "Без файла",
    "w_need_document": "Нужен файл, отправленный как документ (скрепка, «Файл»).",
    "w_ask_manager_text": "Пришлите текст, который клиент увидит после оплаты, например «Мы скоро с вами свяжемся».",
    "w_no_access": "Этот продукт пока ничего не выдаёт.",
    "w_confirm_delete_product": "Удалить этот продукт? Кнопки покупки для него тоже удалятся.",
    "w_pay_title": "Оплаты и язык",
    "w_pay_on": "✅ {method}: включено ({currency})",
    "w_pay_off": "▫️ {method}: выключено",
    "w_method_stars": "Telegram Stars",
    "w_method_telegram": "Банковские карты (Telegram)",
    "w_method_yookassa": "ЮKassa",
    "w_method_crypto": "Crypto Pay",
    "w_method_manual": "Ручной перевод",
    "w_pay_more": "Карты, ЮKassa, крипта и ручной перевод требуют ключей этих сервисов; см. руководство по оплатам в документации.",
    "w_pay_test": "Тестовый режим (бесплатная тестовая оплата для админов): {state}",
    "w_pay_language": "Язык бота: {language}",
    "w_stars_on": "Включить Telegram Stars",
    "w_stars_off": "Выключить Telegram Stars",
    "w_test_on": "Включить тестовый режим",
    "w_test_off": "Выключить тестовый режим",
    "w_switch_language": "🌐 Сменить язык (ru/en)",
    "w_manager_state": "Чат менеджеров: {state}. Чтобы задать его, добавьте бота в группу и отправьте там /managerchat.",
    "w_manager_set": "Готово: этот чат теперь чат менеджеров. Сюда будут приходить карточки заказов и скриншоты оплат.",
    "w_unavailable": "Конструктору нужен файл воронки, которого в этом запуске нет.",
    "w_error": "Не удалось сохранить изменение, ничего не изменено:\n{error}",
}
