from __future__ import annotations

from typing import Dict

from .owner_build import EN as BUILD_EN
from .owner_build import RU as BUILD_RU

EN: Dict[str, str] = {
    "unknown_command": "Unknown command. Admin commands: /admin /stats /leads /payments /user /grant /revoke /refund /erase /broadcast /reload",
    "telegram_refused": "Telegram refused: {error}",
    "your_id": "Your id: {user}\nThis chat id: {chat}",
    "yes": "yes",
    "no": "no",
    "no_end": "no end",
    "user_word": "user",
    "chat_id_hint": "This chat id: {chat}. Copy it into funnel.yaml, then delete this message.",
    "status_pending": "pending",
    "status_awaiting_proof": "awaiting screenshot",
    "status_review": "on review",
    "status_paid": "paid",
    "status_failed": "failed",
    "status_expired": "expired",
    "status_refunded": "refunded",
    "status_rejected": "rejected",
    "status_active": "active",
    "status_ended": "ended",
    "stats_users": "Users: {users} (+{day} today, +{week} this week), blocked the bot: {blocked}",
    "stats_buyers": "Buyers: {buyers} ({share} of users), payments: {payments}, refunded: {refunded}, waiting: {pending}",
    "stats_access": "Active access: {n}",
    "stats_revenue": "Revenue {currency}: total {total}, 7 days {week}, 24 h {day}",
    "stats_steps": "Where users are now: {items}",
    "stats_sources": "Sources: {items}",
    "leads_caption": "{n} users",
    "no_payments": "No payments yet.",
    "user_line": "source: {source}, step: {step}, consent: {consent}, blocked: {blocked}, stopped: {stopped}, erased: {erased}",
    "user_answers": "answers: {answers}",
    "user_payment": "payment {line}",
    "user_access": "access {product} chat {chat} until {until} {status}",
    "usage_user": "Usage: /user <id or @username>",
    "usage_grant": "Usage: /grant <user id or @username> <product id>",
    "usage_revoke": "Usage: /revoke <user id or @username> <product id>",
    "usage_refund": "Usage: /refund <order number> (see /payments or /user)",
    "usage_erase": "Usage: /erase <user id or @username>",
    "user_not_started": "That user has not opened the bot yet, so the bot cannot write to them.",
    "unknown_product": "Unknown product. Available: {items}",
    "granted": "Granted '{product}' to {user}.",
    "unknown_user": "Unknown user.",
    "no_active_access": "No active access to that product.",
    "revoked": "Access ended for {removed} of {total}.{note}",
    "revoke_left": " {left} could not be removed yet: check that the bot is an admin of the chat.",
    "refund_not_paid": "Order {id} is {status}, nothing to refund.",
    "refund_stars": "Stars returned to the customer.",
    "refund_fake": "Nothing to return: it was not a real payment.",
    "refund_manual": "Money was NOT returned automatically: refund it in the {method} account.",
    "refund_done": "Order {id} marked as refunded, access ended for {removed}. {note}",
    "erased": "Personal data of {user} erased. Payment records are kept for accounting.",
    "reload_na": "Reload is not available here.",
    "reload_errors": "The funnel file has errors, the old version keeps running:\n{errors}",
    "reload_ok": "Reloaded: {steps} steps, {products} products.",
    "reload_payments": "Payment settings changed: restart the bot to apply them.",
    "reload_warning": "warning: {warning}",
    "bc_unknown_segment": "Unknown segment. Segments: {segments}",
    "bc_nobody": "Nobody matches this segment.",
    "bc_send": "Send to {n}",
    "bc_ask": "This message will be copied to {n} users (segment '{segment}'). Users who pressed /stop are skipped.",
    "bc_hint": "Easier way: open /admin and press Broadcast.\nOr reply to the message you want to send with /broadcast <segment>.\nSegments: {segments}",
    "bc_handled": "Already handled",
    "bc_cancelled": "Broadcast cancelled.",
    "bc_started": "Broadcast started: {n} users.",
    "bc_finished": "Broadcast finished: delivered {sent}, failed {failed} (blocked users are excluded next time).",
    "cancel": "Cancel",
    "back": "← Back",
    "back_panel": "← Panel",
    "back_payments": "← Payments",
    "back_customer": "← Customer",
    "menu_text": "Control panel. Everything here works with buttons.",
    "m_stats": "📊 Stats",
    "m_leads": "👥 Leads (CSV)",
    "m_broadcast": "📣 Broadcast",
    "m_payments": "💳 Payments",
    "m_find": "🔎 Find user",
    "m_health": "🩺 Health check",
    "m_reload": "🔄 Reload funnel",
    "refresh": "🔄 Refresh",
    "check_again": "🔄 Check again",
    "claim_no": "Nothing to claim: the bot already has an administrator, or the code is wrong.",
    "claim_ok": "You are now the administrator of this bot. Press the button to open the control panel.",
    "claim_btn": "⚙️ Open control panel",
    "find_prompt": "Send me the user's id or @username.",
    "find_none": "No such user. They must have opened the bot at least once.",
    "h_channel": "{icon} channel {chat}: {text}",
    "h_channel_ok": "the bot can invite and remove members",
    "h_manager_set": "✅ manager chat {chat} is set",
    "h_manager_none": "⚠️ manager chat is not set: manager buttons and manual payments are off",
    "h_provider_ok": "✅ {name}: {text}",
    "h_provider_bad": "❌ {name}: {error}",
    "h_waiting": "{icon} paid orders waiting for delivery: {n}",
    "h_stars_off": "⚠️ Stars are off: Telegram's rules require Stars for digital goods and services",
    "h_test_mode": "⚠️ test mode is on (admins see a free test payment button)",
    "b_prompt": "Send me the message you want to broadcast: text, photo, video, voice or a file, exactly as your customers should see it.",
    "seg_prompt": "Got it. Who should receive this message?",
    "seg_all": "Everyone",
    "seg_paid": "Buyers",
    "seg_unpaid": "Not bought yet",
    "seg_active": "Active access",
    "seg_expired": "Access ended",
    "seg_test": "Only me (test)",
    "by_step": "By step…",
    "by_source": "By source…",
    "step_prompt": "Users who are now on this step:",
    "source_prompt": "Users who came from this source (?start=… link):",
    "source_none": "No sources yet: share links like t.me/your_bot?start=ads1 to track where users come from.",
    "draft_gone": "The draft is gone. Start again from Broadcast.",
    "p_list": "Latest payments. Tap one to see details or refund it.",
    "p_detail": "user {user} {line}",
    "btn_refund": "↩️ Refund",
    "btn_customer": "👤 Customer",
    "no_order": "No such order.",
    "refund_confirm": "Refund order #{id}? Access given by this order will end.",
    "yes_refund": "Yes, refund",
    "no_btn": "No",
    "refund_refused": "Telegram refused the refund: {error}",
    "u_give": "🎁 Give access",
    "u_take": "⛔ Take access",
    "u_erase": "🗑 Erase data",
    "give_prompt": "Give which product? The customer gets it as if they had paid.",
    "given": "Done: '{title}' given to {user}.",
    "unknown_user_product": "Unknown user or product.",
    "take_none": "This user has no active channel access.",
    "take_prompt": "Take away which access? The customer is removed from the channel.",
    "grant_until": "{product} (until {until})",
    "taken_ok": "Done: removed from the channel.",
    "taken_fail": "Could not remove them: check that the bot is an administrator of the channel.",
    "no_access": "No such access.",
    "erase_confirm": "Erase personal data of {user} and end their access? Payment records stay for accounting.",
    "yes_erase": "Yes, erase",
    "erased_done": "Personal data of {user} erased.",
    "no_user": "No such user.",
    "alert_manager_chat": "cannot write to the manager chat: {error}",
    "alert_invoice": "cannot send an invoice ({method}): {error}",
    "alert_create": "{method} refused to create a payment: {error}",
    "alert_unmatched": "UNMATCHED PAYMENT: user {user} paid {total} {currency} (charge {charge}, payload {payload}); no such order in the database, check it and refund or grant access by hand",
    "alert_duplicate": "DUPLICATE PAYMENT: order {order} was paid twice (charges {first} and {second}); refund one",
    "alert_gone": "order {order} was paid for product '{product}' which is no longer in the funnel file",
    "alert_deliver": "delivery of order {order} failed and will be retried: {error}",
    "alert_join": "cannot answer join requests in chat {chat}: {error}; is the bot an admin there?",
    "alert_remove": "cannot remove user {user} from chat {chat} after {tries} tries: {error}; is the bot an admin with the ban-users right?",
    "card_manager": "Manager requested",
    "line_step": "step: {step}",
    "line_source": "source: {source}",
    "card_review": "Payment to review",
    "line_order": "order #{id}: {title} — {amount}",
    "btn_approve": "✅ Approve",
    "btn_reject": "❌ Reject",
    "already_processed": "Already processed",
    "verdict_approved": "Order #{id}: approved by {who} ✅",
    "verdict_rejected": "Order #{id}: rejected by {who} ❌",
    "card_paid": "New paid order",
    "line_paid": "order #{id}: {title} — {amount} via {method}",
    **BUILD_EN,
}

RU: Dict[str, str] = {
    "unknown_command": "Неизвестная команда. Команды администратора: /admin /stats /leads /payments /user /grant /revoke /refund /erase /broadcast /reload",
    "telegram_refused": "Telegram отказал: {error}",
    "your_id": "Ваш id: {user}\nid этого чата: {chat}",
    "yes": "да",
    "no": "нет",
    "no_end": "без срока",
    "user_word": "клиент",
    "chat_id_hint": "id этого чата: {chat}. Скопируйте его в funnel.yaml и удалите это сообщение.",
    "status_pending": "ожидает оплаты",
    "status_awaiting_proof": "ждём скриншот",
    "status_review": "на проверке",
    "status_paid": "оплачен",
    "status_failed": "не удался",
    "status_expired": "просрочен",
    "status_refunded": "возвращён",
    "status_rejected": "отклонён",
    "status_active": "действует",
    "status_ended": "закончился",
    "stats_users": "Пользователи: {users} (+{day} за сутки, +{week} за неделю), заблокировали бота: {blocked}",
    "stats_buyers": "Покупатели: {buyers} ({share} пользователей), платежей: {payments}, возвратов: {refunded}, в ожидании: {pending}",
    "stats_access": "Действующих доступов: {n}",
    "stats_revenue": "Выручка {currency}: всего {total}, за 7 дней {week}, за 24 ч {day}",
    "stats_steps": "Где сейчас пользователи: {items}",
    "stats_sources": "Источники: {items}",
    "leads_caption": "пользователей: {n}",
    "no_payments": "Платежей пока нет.",
    "user_line": "источник: {source}, шаг: {step}, согласие: {consent}, заблокировал: {blocked}, без рассылок: {stopped}, удалён: {erased}",
    "user_answers": "ответы: {answers}",
    "user_payment": "платёж {line}",
    "user_access": "доступ {product} чат {chat} до {until} {status}",
    "usage_user": "Использование: /user <id или @username>",
    "usage_grant": "Использование: /grant <id или @username> <id продукта>",
    "usage_revoke": "Использование: /revoke <id или @username> <id продукта>",
    "usage_refund": "Использование: /refund <номер заказа> (список: /payments или /user)",
    "usage_erase": "Использование: /erase <id или @username>",
    "user_not_started": "Этот человек ещё не открывал бота, поэтому бот не может ему написать.",
    "unknown_product": "Нет такого продукта. Доступны: {items}",
    "granted": "Продукт «{product}» выдан пользователю {user}.",
    "unknown_user": "Неизвестный пользователь.",
    "no_active_access": "Нет действующего доступа к этому продукту.",
    "revoked": "Доступ закрыт у {removed} из {total}.{note}",
    "revoke_left": " Не удалось убрать пока {left}: проверьте, что бот админ чата.",
    "refund_not_paid": "Заказ {id}: {status}, возвращать нечего.",
    "refund_stars": "Звёзды возвращены покупателю.",
    "refund_fake": "Возвращать нечего: это был не настоящий платёж.",
    "refund_manual": "Деньги автоматически НЕ возвращены: верните их в кабинете {method}.",
    "refund_done": "Заказ {id} отмечен как возвращённый, доступ закрыт у {removed}. {note}",
    "erased": "Личные данные {user} удалены. Записи о платежах сохранены для бухгалтерии.",
    "reload_na": "Перезагрузка здесь недоступна.",
    "reload_errors": "В файле воронки есть ошибки, работает старая версия:\n{errors}",
    "reload_ok": "Перезагружено: шагов {steps}, продуктов {products}.",
    "reload_payments": "Настройки оплат изменились: перезапустите бота, чтобы они вступили в силу.",
    "reload_warning": "предупреждение: {warning}",
    "bc_unknown_segment": "Неизвестный сегмент. Сегменты: {segments}",
    "bc_nobody": "В этот сегмент никто не попал.",
    "bc_send": "Отправить {n}",
    "bc_ask": "Сообщение будет скопировано {n} пользователям (сегмент «{segment}»). Кто нажал /stop, пропускается.",
    "bc_hint": "Проще так: откройте /admin и нажмите «Рассылка».\nИли ответьте на нужное сообщение командой /broadcast <сегмент>.\nСегменты: {segments}",
    "bc_handled": "Уже обработано",
    "bc_cancelled": "Рассылка отменена.",
    "bc_started": "Рассылка запущена: {n} пользователей.",
    "bc_finished": "Рассылка завершена: доставлено {sent}, ошибок {failed} (заблокировавшие бота в следующий раз исключаются).",
    "cancel": "Отмена",
    "back": "← Назад",
    "back_panel": "← В панель",
    "back_payments": "← К платежам",
    "back_customer": "← К клиенту",
    "menu_text": "Панель управления. Здесь всё работает кнопками.",
    "m_stats": "📊 Статистика",
    "m_leads": "👥 Клиенты (CSV)",
    "m_broadcast": "📣 Рассылка",
    "m_payments": "💳 Платежи",
    "m_find": "🔎 Найти клиента",
    "m_health": "🩺 Проверка бота",
    "m_reload": "🔄 Перезагрузить воронку",
    "refresh": "🔄 Обновить",
    "check_again": "🔄 Проверить снова",
    "claim_no": "Нечего забирать: у бота уже есть администратор или код неверный.",
    "claim_ok": "Теперь вы администратор этого бота. Нажмите кнопку, чтобы открыть панель управления.",
    "claim_btn": "⚙️ Открыть панель управления",
    "find_prompt": "Пришлите id или @username клиента.",
    "find_none": "Такого клиента нет. Он должен хотя бы раз открыть бота.",
    "h_channel": "{icon} канал {chat}: {text}",
    "h_channel_ok": "бот может приглашать и удалять участников",
    "h_manager_set": "✅ чат менеджеров {chat} задан",
    "h_manager_none": "⚠️ чат менеджеров не задан: кнопки менеджера и ручные оплаты выключены",
    "h_provider_ok": "✅ {name}: {text}",
    "h_provider_bad": "❌ {name}: {error}",
    "h_waiting": "{icon} оплаченных заказов, ожидающих выдачи: {n}",
    "h_stars_off": "⚠️ Stars выключены: правила Telegram требуют Stars для цифровых товаров и услуг",
    "h_test_mode": "⚠️ тестовый режим включён (админам показывается бесплатная тестовая оплата)",
    "b_prompt": "Пришлите сообщение для рассылки: текст, фото, видео, голосовое или файл, ровно в том виде, как его увидят клиенты.",
    "seg_prompt": "Принято. Кому отправить это сообщение?",
    "seg_all": "Всем",
    "seg_paid": "Покупателям",
    "seg_unpaid": "Ещё не купили",
    "seg_active": "С действующим доступом",
    "seg_expired": "Доступ закончился",
    "seg_test": "Только мне (тест)",
    "by_step": "По шагу…",
    "by_source": "По источнику…",
    "step_prompt": "Пользователи, которые сейчас на этом шаге:",
    "source_prompt": "Пользователи, пришедшие из этого источника (ссылка ?start=…):",
    "source_none": "Источников пока нет: раздавайте ссылки вида t.me/your_bot?start=ads1, чтобы видеть, откуда приходят люди.",
    "draft_gone": "Черновик потерян. Начните заново с «Рассылка».",
    "p_list": "Последние платежи. Нажмите на платёж, чтобы открыть детали или сделать возврат.",
    "p_detail": "клиент {user} {line}",
    "btn_refund": "↩️ Вернуть деньги",
    "btn_customer": "👤 Клиент",
    "no_order": "Такого заказа нет.",
    "refund_confirm": "Вернуть деньги по заказу #{id}? Выданный им доступ будет закрыт.",
    "yes_refund": "Да, вернуть",
    "no_btn": "Нет",
    "refund_refused": "Telegram отказал в возврате: {error}",
    "u_give": "🎁 Выдать доступ",
    "u_take": "⛔ Забрать доступ",
    "u_erase": "🗑 Стереть данные",
    "give_prompt": "Какой продукт выдать? Клиент получит его так, как если бы оплатил.",
    "given": "Готово: «{title}» выдан пользователю {user}.",
    "unknown_user_product": "Неизвестный пользователь или продукт.",
    "take_none": "У этого клиента нет действующего доступа в канал.",
    "take_prompt": "Какой доступ забрать? Клиент будет удалён из канала.",
    "grant_until": "{product} (до {until})",
    "taken_ok": "Готово: клиент удалён из канала.",
    "taken_fail": "Не удалось убрать: проверьте, что бот администратор канала.",
    "no_access": "Такого доступа нет.",
    "erase_confirm": "Стереть личные данные {user} и закрыть доступ? Записи о платежах останутся для бухгалтерии.",
    "yes_erase": "Да, стереть",
    "erased_done": "Личные данные {user} удалены.",
    "no_user": "Такого клиента нет.",
    "alert_manager_chat": "не могу написать в чат менеджеров: {error}",
    "alert_invoice": "не удалось отправить счёт ({method}): {error}",
    "alert_create": "{method} отказал в создании платежа: {error}",
    "alert_unmatched": "ПЛАТЁЖ БЕЗ ЗАКАЗА: пользователь {user} заплатил {total} {currency} (операция {charge}, payload {payload}); такого заказа нет в базе. Проверьте и верните деньги или выдайте доступ вручную",
    "alert_duplicate": "ДВОЙНОЙ ПЛАТЁЖ: заказ {order} оплачен дважды (операции {first} и {second}); верните один из них",
    "alert_gone": "заказ {order} оплачен за продукт «{product}», которого больше нет в файле воронки",
    "alert_deliver": "выдача заказа {order} не удалась, будет повторена: {error}",
    "alert_join": "не могу отвечать на заявки в чате {chat}: {error}; бот админ этого чата?",
    "alert_remove": "не могу удалить пользователя {user} из чата {chat} после {tries} попыток: {error}; бот админ с правом блокировать участников?",
    "card_manager": "Запрос менеджера",
    "line_step": "шаг: {step}",
    "line_source": "источник: {source}",
    "card_review": "Платёж на проверку",
    "line_order": "заказ #{id}: {title} — {amount}",
    "btn_approve": "✅ Подтвердить",
    "btn_reject": "❌ Отклонить",
    "already_processed": "Уже обработано",
    "verdict_approved": "Заказ #{id}: подтвердил(а) {who} ✅",
    "verdict_rejected": "Заказ #{id}: отклонил(а) {who} ❌",
    "card_paid": "Новый оплаченный заказ",
    "line_paid": "заказ #{id}: {title} — {amount}, способ: {method}",
    **BUILD_RU,
}

TABLES = {"en": EN, "ru": RU}

